openapi: 3.0.3
info:
  title: JukeBox Playlist API
  version: 1.0.0
  description: API for managing user-created playlists in the JukeBox app

servers:
  - url: http://localhost:3000/api

paths:
  /playlists:
    get:
      summary: Get all playlists
      responses:
        '200':
          description: List of playlists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Playlist'
        '500':
          description: Server error

    post:
      summary: Create a new playlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPlaylist'
      responses:
        '201':
          description: Playlist created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  playlist:
                    $ref: '#/components/schemas/Playlist'
        '400':
          description: Invalid playlist data
        '500':
          description: Server error

  /playlists/{id}:
    delete:
      summary: Delete a playlist
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Playlist deleted successfully
        '404':
          description: Playlist not found
        '500':
          description: Server error

    put:
      summary: Update playlist name
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                playlist_name:
                  type: string
      responses:
        '200':
          description: Playlist updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: Playlist name is required
        '404':
          description: Playlist not found
        '500':
          description: Server error

  /playlists/{playlistId}/songs/{trackId}:
    delete:
      summary: Remove a song from a playlist
      parameters:
        - name: playlistId
          in: path
          required: true
          schema:
            type: string
        - name: trackId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Song removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'
        '404':
          description: Playlist or song not found
        '500':
          description: Server error

components:
  schemas:
    Song:
      type: object
      properties:
        track_id:
          type: string
        title:
          type: string
        artist:
          type: string
        album:
          type: string
        duration:
          type: string
        image:
          type: string

    Playlist:
      type: object
      properties:
        _id:
          type: string
        playlist_name:
          type: string
        songs:
          type: array
          items:
            $ref: '#/components/schemas/Song'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    NewPlaylist:
      type: object
      required:
        - playlist_name
        - songs
      properties:
        playlist_name:
          type: string
        songs:
          type: array
          items:
            $ref: '#/components/schemas/Song'